apiVersion: apps/v1
kind: Deployment
metadata:
  name: RoomInfo
  labels:
    app: RoomInfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RoomInfo
  template:
    metadata:
      labels:
        app: RoomInfo
    spec:
      containers:
        - name: RoomInfo
          image: username/RoomInfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5